# Generated by Django 3.0.9 on 2020-08-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesa',
            name='token',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpesa',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mpesa',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
